Add default text for each program in .problemconfig
* when a new program file is created it has text echoed into it from .problemconfig
* this can be customized for each file extension

diff --git a/problem b/problem
--- a/problem
+++ b/problem
@@ -4,15 +4,38 @@ function usage(){
   echo -e "error\ncurrect usage: \n./problem (name) -l (lang)"
 }
 
-function openFile(){
+function openFile(){ #file
   if test ".problemconfig"; then
-    re='^defaultapp:'
-    while read line; do
-      if [[ $line =~ $re ]]; then
-        open -a"${line:12}" $1
-        break
-      fi
-    done <.problemconfig
+    file=$(<".problemconfig")
+    re='defaultapp: ([^:]*):'
+    if [[ $file =~ $re ]]; then
+      open -a"${BASH_REMATCH[1]}" $1
+      exit 0
+    else
+      echo "fnf in .problemconfig"
+      exit 1
+    fi
+  else
+    echo "missing .problemconfig"
+    exit 1
+  fi
+}
+
+function writeFile(){ #folder #language
+  if test ".problemconfig"; then
+    re="$2: ([^ ]+) ([^:]*):"
+    file=$(<".problemconfig")
+    if [[ $file =~ $re ]]; then
+      mkdir "$1"
+      touch "$1/${BASH_REMATCH[1]}"
+      echo "${BASH_REMATCH[2]}" > "$1/${BASH_REMATCH[1]}"
+      openFile "$1/${BASH_REMATCH[1]}"
+      exit 0
+    else
+      echo "fnf in .problemconfig"
+      exit 1
+    fi
+
   else
     echo "missing .problemconfig"
     exit 1
@@ -26,67 +49,7 @@ fi
 
 if [ $# -eq 3 ]; then
   if [ $2 == "-l" ]; then
-    mkdir $1
-
-    case $3 in
-      cpp)
-      touch "$1/makefile"
-      echo -e "bin: main.cpp\n\tg++ -std=c++11 -Wall -Wextra -pedantic -O2 -o bin main.cpp" >> "$1/makefile"
-      if test ".problemconfig"; then
-        re='^cpp:'
-        while read line; do
-          if [[ $line =~ $re ]]; then
-            touch "$1/${line:5}"
-            openFile "$1/${line:5}"
-            break
-          fi
-        done <.problemconfig
-      else
-        echo "missing .problemconfig"
-        exit 1
-      fi
-      exit 0
-      ;;
-
-      python)
-      if test ".problemconfig"; then
-        re='^python:'
-        while read line; do
-          if [[ $line =~ $re ]]; then
-            touch "$1/${line:8}"
-            openFile "$1/${line:8}"
-            break
-          fi
-        done <.problemconfig
-      else
-        echo "missing .problemconfig"
-        exit 1
-      fi
-      exit 0
-      ;;
-
-      java)
-      if test ".problemconfig"; then
-        re='^java:'
-        while read line; do
-          if [[ $line =~ $re ]]; then
-            touch "$1/${line:6}"
-            openFile "$1/${line:6}"
-            break
-          fi
-        done <.problemconfig
-      else
-        echo "missing .problemconfig"
-        exit 1
-      fi
-      exit 0
-      ;;
-
-      *)
-      echo -e"$(usage)"
-      exit 1
-      ;;
-    esac
+    writeFile "$1" "$3"
   fi
   echo -e "$(usage)"
   exit 1
